development:
  sessions:
    default:
      database: messenger_development
      hosts:
        - localhost:27017
  options:
    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    raise_not_found_error: false
test:
  sessions:
    default:
      database: messenger_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        safe: true
        skip_version_check: true
